### ISSUE TITLE
Additional data to the response

### ISSUE THREAD

**Issue by gray-adeyi** [gray-adeyi/paystack-sdk#33]
Currently, `PaystackResponse` only contains the `statusCode`, `status`, `message`, `data`. some endpoints include additional data that is not currently captured by the `PaystackResponse`. add the following missing fields `meta`, `type` and `code` to the `PaystackResponse` type and configure the `deserilizeResponse` in the `restClient` to include this additional data in the returned response

**Comment by gray-adeyi** [comment]
All pull requests should be send to the dev branch

**Comment by Hallowdread** [comment]
On it
